Rainforest/config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: %i(new create destroy)
  resource :users, only: %i(new create)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products do
    resources :reviews, only: %i(create edit destroy new update)
  end


end

Rainforest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def user_is_logged_in
      false
  end
end

Rainforest/app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  validates :name, :description, :price_in_cents, :url, presence: true
  validates :price_in_cents, numericality: { greater_than: 0 }
  def price_in_dollar
    price_in_cents/100.0
  end
end

Rainforest/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :users
  validates :description, presence: true
end

Rainforest/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true;
  has_many :reviews
end

Rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user

      redirect_to new_sessions_path, alert: "You are not autherized, Please login"

    end
  end

  def ensure_user_owns_review
    unless current_user == @review.user_id
      flash[:alert] = "Please log in"
      redirect_to new_sessions_path
    end

  end

end

Rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :ensure_logged_in, except: [:show, :index]



  def index

    @products = Product.all

  end

  def new

    @product = Product.new


  end

  def edit

    load_product
    # @product = Product.find(params[:id])

  end

  def show

    # we find the instance of thhe product using params[:id] store it in a variable to be used in the view
    load_product
    # @product = Product.find(params[:id])
    @review = Review.new

  end

  def update

    load_product
    # @product = Product.find(params[:id])

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      redirect_to product_url(@product.id)
    else
      redirect_to product_path
    end

  end

  def create

    @product = Product.new

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      redirect_to product_url(@product.id)
    else
      render :new
    end

  end

  def destroy

    # @product = Product.find(params[:id])

    load_product

    @product.destroy

    redirect_to root_path

  end


  def load_product
  @product = Product.find(params[:id])
  end
end

Rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :ensure_logged_in, except: [:show, :index]
  before_action :ensure_user_owns_review, only: [:edit, :update, :destroy]

def create

  @review = Review.new

  @review.description = params[:review][:description]
  @review.product_id = params[:product_id]
  @review.save

  redirect_to product_url(params[:product_id])

end

def edit

  @review = Review.find(params[:id])
  @product = Product.find(params[:product_id])

end

def update

  @review = Review.find(params[:id])

  @review.description = params[:review][:description]
  @review.product_id = params[:product_id]
  @review.save

  redirect_to product_path(params[:product_id])

end

def destroy

  @product = Product.find(params[:product_id])
  @review = Review.find(params[:id])

  @review.destroy

  redirect_to product_url(@product.id)
end

end

Rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    u = User.find_by(email: params[:session][:email])

    if u && u.authenticate(params[:session][:password])

      session[:user_id] = u.id

      redirect_to root_url

    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

Rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password]

    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
end

Rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

Rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

Rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Armata" rel="stylesheet">
  </head>



  <body class="container">
    <header class="header">
      <h1 class="logo"> <a href="/products"> Rainforest</a></h1>
          <% if current_user %>
      <%= link_to 'Logout', sessions_path, method: :delete %>
    <% else %>
      <p> <%= link_to 'New Account', new_users_path %> |
      <%= link_to 'Login', new_sessions_path %> </p>
    <% end %>
    </p>
      <nav class="navbar">
        <a><%= link_to 'Home', root_path %></a>
        <a><%= link_to 'Products', products_path %></a>
        <a><%= link_to 'Add New Product', new_product_path %></a>
      </nav>
    </header>

    <section class="wrapper">

      <%= yield %>

    </section>

    <footer>
      <h5> Developed by Hasan | Karen | Gustavo  </h5>
    </footer>
  </body>
</html>

Rainforest/app/views/products/_product_form.html.erb
<%= form_for product do |f|  %>

    <h4><%= f.label :name %></h4>
    <h4><%= f.text_field :name %></h4>

    <h4><%= f.label :description %></h4>
    <h4><%= f.text_field :description %></h4>

    <h4><%= f.label :price_in_cents %></h4>
    <h4><%= f.text_field :price_in_cents %></h4>

    <h4><%= f.label :url %></h4>
    <h4><%= f.text_field :url %></h4>

    <h4><%= f.submit %></h4>

<% end %>

<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this article from being saved:</h2>


    <ul>
    <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Rainforest/app/views/products/_product_individual.html.erb
<div class="picture">
  <%= link_to(image_tag(product.url), product_path(product)) %>
</div>

<div class="text">
  <%= link_to "#{ product.name }", product_path(product) %>
  <h3 class="description">
    Description: <%= product.description %>
    <br>
    Price: <%= product.price_in_dollar %> dollars
  </h3>
</div>

Rainforest/app/views/products/_review.html.erb
<%= form_for(@review , url: product_reviews_path(@product.id)) do |f|  %>

  <%= f.text_field :description %>

  <%= f.submit %>

  <% end %>

Rainforest/app/views/products/edit.html.erb
<div class="edit">
  <h1>Edit</h1>

  <div class="form">
    <%= render 'product_form', product: @product %>
  </div>
</div>

Rainforest/app/views/products/index.html.erb
<section class="index">
  <% @products.each do |product| %>


    <div class="single">
      <%= render "product_individual", product: product, price_in_dollar: product.price_in_cents/100.0 %>
    </div>

  <% end %>
</section>

Rainforest/app/views/products/new.html.erb
<div class="new">
  <h1>New Product</h1>

  <div class="form">
    <%= render 'product_form', product: @product %>
  </div>
</div>

Rainforest/app/views/products/show.html.erb
<div class="show">
  <%= render "product_individual", product: @product %>

  <span class="links">
    <%= link_to "Edit", edit_product_path %> |

    <%= link_to "Delete", product_url(@product), method: :delete, data: {confirm: "Are you sure you want to delete this product #{ @product.name }?"} %>
  </span>


  <!-- First we will find the review for the product -->
  <!--  Display the review (review description)  we will show the timestamp-->
  <!--  have a form to add review we make sure the product_id is the same as params[:id] -->
</div>

<div class="review">
  <h2 class="label">Reviews:</h2>
  <% @product.reviews.each do |review| %>

  <ul>
    <li>
      <span class="review-description"><%= review.description %></span>

      <span class="time"><%= review.created_at.asctime %></span>

      <br/>

      <span class="links">
        <%= link_to 'Edit', edit_product_review_path(@product.id,review) %> |
        <%= link_to "Delete", product_review_url(@product.id, review), method: :delete, data: {confirm: "Are you sure you want to delete \"#{ review.description }\"?"} %>
      </span>
    </li>
  </ul>

  <% end %>
  <%=  render 'review' ,locals:{ review: @review , product_id: @product.id } %>
</div>

Rainforest/app/views/reviews/_product_individual.html.erb
<h2><%= link_to "Name: #{ product.name }", product_path(product) %></h2>
<p>
  Description: <%= product.description %>
  <br>
  Price: <%= product.price_in_cents %> Cents
</p>

Rainforest/app/views/reviews/_review.html.erb
<%= form_for(@review , url: product_review_path(@product,@review)) do |f|  %>

  <%= f.text_field :description %>

  <%= f.submit %>

  <% end %>

Rainforest/app/views/reviews/edit.html.erb
<h1>Update Review</h1>


<%=  render 'review' ,locals:{ review: @review , product_id: @product.id } %>

Rainforest/app/views/users/new.html.erb
<div class="new">
  <h1>New User</h1>

<div class="form">
  <% if @user.errors.any?  %>
    <% @user.errors.full_messages.each do |m| %>
    <p>
      <%= m %>
    </p>
      <% end %>
  <% end %>
<%= form_for @user do |f| %>

    <h4> <%= f.label :email %> </h4>
    <h4><%= f.email_field :email %> </h4>

    <h4><%= f.label :password %> </h4>
    <h4><%= f.password_field :password %> </h4>

    <h4><%= f.label :password_confirmation %> </h4>
    <h4><%= f.password_field :password_confirmation %> </h4>

  <h4></h4><%= f.submit 'Sign Up' %> </h4>

<% end %>

</div>
</div>